; [SECTION_0]
; IN=0.988
; OUT=0.048
; TEXT=Turn 1

[SECTION_1]
IN=0.090
OUT=0.180
TEXT=Andretti Hairpin

[SECTION_2]
IN=0.190
OUT=0.250
TEXT=Turn 3

[SECTION_3]
IN=0.260
OUT=0.330
TEXT=Turn 4

[SECTION_4]
IN=0.390
OUT=0.470
TEXT=Turn 5

[SECTION_5]
IN=0.515
OUT=0.575
TEXT=Turn 6

[SECTION_6]
IN=0.575
OUT=0.650
TEXT=Rahal Straight

[SECTION_7]
IN=0.650
OUT=0.715
TEXT=The Corkscrew

[SECTION_8]
IN=0.715
OUT=0.800
TEXT=Rainey Curve

[SECTION_9]
IN=0.800
OUT=0.870
TEXT=Turn 10

[SECTION_10]
IN=0.880
OUT=0.940
TEXT=Turn 11

[SECTION_11]
IN=0.0
OUT=0.39
TEXT=Secteur 1

[SECTION_12]
IN=0.39
OUT=0.725
TEXT=Secteur 2

[SECTION_13]
IN=0.725
OUT=1.0
TEXT=Secteur 3

[SECTION_14]
IN=0.0
OUT=1.0
TEXT=Tour complet
